use super::messages::*;

use ff::{Field, PrimeField};
use group::{Group, GroupEncoding};
use num_bigint::BigUint;
use num_traits::One;
use rand_core::{CryptoRng, RngCore};
use sha3::{Digest, Sha3_256};

/// We prove the following relation (informally stated) for secrets r and s:
///  1) c_0 = g^r and
///  2) c_1 = pk_0^r * g^s and
///  3) ck = h^s and
///  4) c_i = DLEQ(c_0, pk_i^r) or DLEQ(c_0, pk_i^r / g) for i > 1
///
/// This enforces that the ElGamal ciphertext is well-formed, that the secret
/// key is embedded correctly, and that each input is either 0 or 1.
pub fn create_proof_binary<G: Group + GroupEncoding, R: RngCore + CryptoRng>(
    key: &ClientKey<G>,
    r: G::Scalar,
    input: &[u32],
    encoding: &Encoding<G>,
    rng: &mut R,
) -> Proof<G> {
    // Generate commitments (and simulated transcripts) for claim 4
    let mut r_x_rand = Vec::with_capacity(input.len()); // Randomness for real branch
    let mut comm_g_x0 = Vec::with_capacity(input.len());
    let mut comm_pk_x0 = Vec::with_capacity(input.len());
    let mut comm_g_x1 = Vec::with_capacity(input.len());
    let mut comm_pk_x1 = Vec::with_capacity(input.len());
    let mut sim_challenges = Vec::with_capacity(input.len());
    let mut sim_responses = Vec::with_capacity(input.len());

    for i in 0..input.len() {
        // Generate simulated transcripts for false paths in claim 4
        let challenge = G::Scalar::random(&mut *rng);
        let response = G::Scalar::random(&mut *rng);
        sim_challenges.push(challenge);
        sim_responses.push(response);

        // Generate commitments
        let r_rand = G::Scalar::random(&mut *rng);
        r_x_rand.push(r_rand);
        match input[i] {
            0 => {
                // Real
                comm_g_x0.push(key.g * r_rand);
                comm_pk_x0.push(key.pks[i + 1] * r_rand);

                // Simulated
                comm_g_x1.push(key.g * response - encoding.rand * challenge);
                comm_pk_x1.push(key.pks[i + 1] * response - (encoding.vals[i] - key.g) * challenge);
            }
            1 => {
                // Simulated
                comm_g_x0.push(key.g * response - encoding.rand * challenge);
                comm_pk_x0.push(key.pks[i + 1] * response - encoding.vals[i] * challenge);

                // Real
                comm_g_x1.push(key.g * r_rand);
                comm_pk_x1.push(key.pks[i + 1] * r_rand);
            }
            _ => panic!("Input should be 0 or 1"),
        }
    }

    // Generate commitments for claims 1-3
    let r_rand = G::Scalar::random(&mut *rng);
    let s_rand = G::Scalar::random(&mut *rng);
    let comm_g_r_rand = key.g * r_rand;
    let comm_pk0_r_rand = key.pks[0] * r_rand;
    let comm_g_s_rand = key.g * s_rand;
    let comm_h_s_rand = key.h * s_rand;

    // Apply fiat-shamir to non-interactively generate challenge
    //
    // TODO: This doesn't include full transcript atm
    let challenge =
        fiat_shamir_challenge::<G>(&[key.g.to_bytes().as_ref(), encoding.rand.to_bytes().as_ref()]);

    // Generate responses for claim 4
    let mut challenges_x = Vec::with_capacity(input.len());
    let mut responses_x0 = Vec::with_capacity(input.len());
    let mut responses_x1 = Vec::with_capacity(input.len());
    for i in 0..input.len() {
        let challenge_real = challenge - sim_challenges[i];
        // Always send the challenge for the zero branch
        match input[i] {
            0 => {
                challenges_x.push(challenge_real);
                responses_x0.push(r_x_rand[i] + challenge_real * r);
                responses_x1.push(sim_responses[i]);
            }
            1 => {
                // Always send the challenge for the zero branch
                challenges_x.push(sim_challenges[i]);
                responses_x0.push(sim_responses[i]);
                responses_x1.push(r_x_rand[i] + challenge_real * r);
            }
            _ => unreachable!(),
        }
    }

    Proof {
        comm_g_r: comm_g_r_rand,
        comm_pk_r: comm_pk0_r_rand,
        comm_g_s: comm_g_s_rand,
        comm_h_s: comm_h_s_rand,
        comm_g_x0,
        comm_pk_x0,
        comm_g_x1,
        comm_pk_x1,
        challenge_x: challenges_x,
        response_r: r_rand + challenge * r,
        response_s: s_rand + challenge * key.secret,
        response_x0: responses_x0,
        response_x1: responses_x1,
    }
}

macro_rules! check_claim {
    ($left:expr, $right:expr) => {
        if $left != $right {
            return false;
        }
    };
}

/// Verify a proof generated by `create_proof_binary`.
pub fn verify_proof_binary<G: Group + GroupEncoding>(
    params: &Params<G>,
    client_index: u32,
    encoding: &Encoding<G>,
    proof: &Proof<G>,
) -> bool {
    // Apply fiat-shamir to generate challenge
    //
    // TODO: This doesn't include full transcript atm
    let challenge = fiat_shamir_challenge::<G>(&[
        params.g.to_bytes().as_ref(),
        encoding.rand.to_bytes().as_ref(),
    ]);

    // Check 1) c_0 = g^r
    check_claim!(
        params.g * proof.response_r,
        proof.comm_g_r + encoding.rand * challenge
    );

    // Check 2) c_1 = pk_0^r * g^s
    check_claim!(
        params.pks[0] * proof.response_r + params.g * proof.response_s,
        proof.comm_pk_r + proof.comm_g_s + encoding.secret * challenge
    );

    // Check 3) ck = h^s
    check_claim!(
        params.h * proof.response_s,
        proof.comm_h_s + params.client_key_comms[client_index as usize] * challenge
    );

    // Check 4) c_i = DLEQ(c_0, pk_i^r) or DLEQ(c_0, pk_i^r / g) for i > 1
    for i in 0..encoding.vals.len() {
        let challenge_0 = proof.challenge_x[i];
        let challenge_1 = challenge - challenge_0;

        // X=0, check DLEQ(c_0, pk_i^r)
        check_claim!(
            params.g * proof.response_x0[i],
            proof.comm_g_x0[i] + encoding.rand * challenge_0
        );
        check_claim!(
            params.pks[i + 1] * proof.response_x0[i],
            proof.comm_pk_x0[i] + encoding.vals[i] * challenge_0
        );

        // X=1, check DLEQ(c_0, pk_i^r / g)
        check_claim!(
            params.g * proof.response_x1[i],
            proof.comm_g_x1[i] + encoding.rand * challenge_1
        );
        check_claim!(
            params.pks[i + 1] * proof.response_x1[i],
            proof.comm_pk_x1[i] + (encoding.vals[i] - params.g) * challenge_1
        );
    }

    true
}

/// Computes a Fiat-Shamir challenge for the proof system.
fn fiat_shamir_challenge<G: Group + GroupEncoding>(inputs: &[&[u8]]) -> G::Scalar {
    // Compute the hash
    let mut hasher = Sha3_256::new();
    for input in inputs {
        hasher.update(input);
    }
    let bytes = hasher.finalize();

    // Compute the BigUint representation of the modulus
    let modulus_bytes = (G::Scalar::ZERO - G::Scalar::ONE).to_repr();
    let modulus = BigUint::from_bytes_le(modulus_bytes.as_ref()) + BigUint::one();

    // Map the hash value to a scalar value
    let scalar = BigUint::from_bytes_be(&bytes) % modulus;

    // Map the BigUint to a scalar value
    let scalar_byte_length = (G::Scalar::NUM_BITS as usize + 7) / 8;
    let mut bytes = vec![0u8; scalar_byte_length];
    let scalar_bytes = scalar.to_bytes_be();
    let start = bytes.len() - scalar_bytes.len();
    bytes[start..].copy_from_slice(&scalar_bytes);
    bytes.reverse();
    let mut repr = <<G as Group>::Scalar as PrimeField>::Repr::default();
    repr.as_mut().copy_from_slice(&bytes);
    <<G as Group>::Scalar as PrimeField>::from_repr(repr).expect("Error mapping hash to scalar")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::Aggregation;

    use curve25519_dalek::RistrettoPoint;
    use rand::{Rng, rngs::OsRng};

    type G = RistrettoPoint;
    type Agg = crate::protocol::dl::DiscreteLog<G>;

    #[test]
    fn proof_correctness() {
        let length = 5;
        let (params, _sk, cks) = Agg::setup(1, length, &mut OsRng);
        let mut rng = rand::thread_rng();
        for _ in 0..10 {
            let input: Vec<u32> = (0..length)
                .map(|_| if rng.gen_bool(0.5) { 1 } else { 0 })
                .collect();
            let r = <G as Group>::Scalar::random(&mut OsRng);
            let encoding = Encoding {
                rand: params.g * r,
                secret: params.pks[0] * r + params.g * cks[0].secret,
                vals: input
                    .iter()
                    .enumerate()
                    .map(|(i, v)| {
                        params.pks[i + 1] * r + params.g * <G as Group>::Scalar::from(*v as u64)
                    })
                    .collect(),
            };
            let proof = create_proof_binary(&cks[0], r, &input, &encoding, &mut OsRng);
            assert!(
                verify_proof_binary(&params, 0, &encoding, &proof),
                "Proof verification failed for input {:?}",
                input
            );
        }
    }

    /// Tests that tampered data is rejected by proof verification.
    #[test]
    fn proof_soundness_tampering() {
        let length = 5;
        let (params, _sk, cks) = Agg::setup(1, length, &mut OsRng);
        let mut rng = rand::thread_rng();
        let input: Vec<u32> = (0..length)
            .map(|_| if rng.gen_bool(0.5) { 1 } else { 0 })
            .collect();
        let r = <G as Group>::Scalar::random(&mut OsRng);
        let encoding = Encoding {
            rand: params.g * r,
            secret: params.pks[0] * r + params.g * cks[0].secret,
            vals: input
                .iter()
                .enumerate()
                .map(|(i, v)| {
                    params.pks[i + 1] * r + params.g * <G as Group>::Scalar::from(*v as u64)
                })
                .collect(),
        };
        let proof = create_proof_binary(&cks[0], r, &input, &encoding, &mut OsRng);

        // Verify the original proof is valid
        assert!(verify_proof_binary(&params, 0, &encoding, &proof));

        // Try tampering each location of the proof and assert that it is rejected
        let mut bad_encoding = encoding.clone();
        bad_encoding.rand = params.g * <G as Group>::Scalar::random(&mut OsRng);
        assert!(!verify_proof_binary(&params, 0, &bad_encoding, &proof));

        let mut bad_encoding = encoding.clone();
        bad_encoding.secret = params.g * <G as Group>::Scalar::random(&mut OsRng);
        assert!(!verify_proof_binary(&params, 0, &bad_encoding, &proof));

        for i in 0..encoding.vals.len() {
            let mut bad_encoding = encoding.clone();
            bad_encoding.vals[i] = params.g * <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &bad_encoding, &proof));
        }

        let mut bad_proof = proof.clone();
        bad_proof.response_r = <G as Group>::Scalar::random(&mut OsRng);
        assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));

        let mut bad_proof = proof.clone();
        bad_proof.response_s = <G as Group>::Scalar::random(&mut OsRng);
        assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));

        for i in 0..proof.response_x0.len() {
            let mut bad_proof = proof.clone();
            bad_proof.response_x0[i] = <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));
        }

        for i in 0..proof.response_x1.len() {
            let mut bad_proof = proof.clone();
            bad_proof.response_x1[i] = <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));
        }

        for i in 0..proof.challenge_x.len() {
            let mut bad_proof = proof.clone();
            bad_proof.challenge_x[i] = <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));
        }

        let mut bad_proof = proof.clone();
        bad_proof.comm_g_r = params.g * <G as Group>::Scalar::random(&mut OsRng);
        assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));

        for i in 0..proof.comm_g_x0.len() {
            let mut bad_proof = proof.clone();
            bad_proof.comm_g_x0[i] = params.g * <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));
        }

        for i in 0..proof.comm_g_x1.len() {
            let mut bad_proof = proof.clone();
            bad_proof.comm_g_x1[i] = params.g * <G as Group>::Scalar::random(&mut OsRng);
            assert!(!verify_proof_binary(&params, 0, &encoding, &bad_proof));
        }
    }

    /// Tests that wrong client indices are rejected by proof verification.
    #[test]
    fn proof_soundness_wrong_client() {
        let num_clients = 3;
        let length = 5;
        let (params, _sk, cks) = Agg::setup(num_clients, length, &mut OsRng);
        let mut rng = rand::thread_rng();
        let input: Vec<u32> = (0..length)
            .map(|_| if rng.gen_bool(0.5) { 1 } else { 0 })
            .collect();
        let r = <G as Group>::Scalar::random(&mut OsRng);
        let encoding = Encoding {
            rand: params.g * r,
            secret: params.pks[0] * r + params.g * cks[0].secret,
            vals: input
                .iter()
                .enumerate()
                .map(|(i, v)| {
                    params.pks[i + 1] * r + params.g * <G as Group>::Scalar::from(*v as u64)
                })
                .collect(),
        };
        let proof = create_proof_binary(&cks[0], r, &input, &encoding, &mut OsRng);

        // Verify with correct client index
        assert!(verify_proof_binary(&params, 0, &encoding, &proof));

        // Verify with wrong client index
        assert!(!verify_proof_binary(&params, 1, &encoding, &proof));
        assert!(!verify_proof_binary(&params, 2, &encoding, &proof));
    }
}
